name: Build, Scan with Trivy & Push to Docker Hub

on:
  workflow_dispatch:   # Trigger manually from GitHub Actions tab

jobs:
  docker-build-scan-push:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code from GitHub
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Log in to Docker Hub (store creds in GitHub Secrets)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3️⃣ Build the Docker image
    - name: Build Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/my-app
        docker build -t $IMAGE_NAME:latest .

    # 4️⃣ Install Trivy (latest)
    - name: Install Trivy
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install -y trivy

    # 5️⃣ Scan Docker image for vulnerabilities
    - name: Scan Docker image with Trivy
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/my-app
        trivy image --exit-code 1 --severity CRITICAL,HIGH $IMAGE_NAME:latest

    # 6️⃣ Push Docker image
    - name: Push Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/my-app
        docker push $IMAGE_NAME:latest