name: Build, Scan with Trivy & Push to Docker Hub

on:
  workflow_dispatch:   # Trigger manually from GitHub Actions tab

jobs:
  docker-build-scan-push:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code from GitHub
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Log in to Docker Hub (store creds in GitHub Secrets)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3️⃣ Build the Docker image
    - name: Build Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/my-app
        docker build -t $IMAGE_NAME:latest .

    # 3️⃣ Install Trivy
    - name: Install Trivy
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install -y trivy

    - name: Scan Docker image with Trivy
      run: |
        IMAGE_NAME=my-app
        mkdir -p trivy-report
        # Scan local image without pulling
        trivy image --skip-update --ignore-unfixed --format table --exit-code 0 --severity CRITICAL,HIGH -o trivy-report/report.txt $IMAGE_NAME:latest
        trivy image --skip-update --ignore-unfixed --format json --exit-code 0 --severity CRITICAL,HIGH -o trivy-report/report.json $IMAGE_NAME:latest
        
        if grep -q "CRITICAL\|HIGH" trivy-report/report.txt; then
          echo "found_vuln=true" >> $GITHUB_ENV
        else
          echo "found_vuln=false" >> $GITHUB_ENV
        fi

    # 5️⃣ Upload Trivy Report as Artifact
    - name: Upload Trivy Report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-vulnerability-report
        path: trivy-report/

    # 6️⃣ Push to Docker Hub only if no vulnerabilities found
    - name: Log in to Docker Hub
      if: env.found_vuln == 'false'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      if: env.found_vuln == 'false'
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/my-app
        docker tag my-app:latest $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest

    # 7️⃣ Stop with failure if vulnerabilities found
    - name: Fail if vulnerabilities found
      if: env.found_vuln == 'true'
      run: |
        echo "❌ Vulnerabilities found! Image not pushed to Docker Hub."
        exit 1
